# Generated by Django 4.1.4 on 2023-01-14 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id_competition', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statsbomb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_women', models.BooleanField(default=False)),
                ('is_youth', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id_season', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statsbomb_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id_competition_edition', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('match_available', models.DateTimeField(editable=False, null=True)),
                ('match_available_360', models.DateTimeField(editable=False, null=True)),
                ('match_updated', models.DateTimeField(null=True)),
                ('match_updated_360', models.DateTimeField(null=True)),
                ('match_outdated', models.BooleanField(default=True)),
                ('match_outdated_360', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_api.competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_api.season')),
            ],
        ),
    ]
