# Generated by Django 4.1.4 on 2022-12-11 16:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('is_women', models.BooleanField(default=False)),
                ('is_youth', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('match_available', models.DateTimeField(null=True)),
                ('match_available_360', models.DateTimeField(null=True)),
                ('match_updated', models.DateTimeField(null=True)),
                ('match_updated_360', models.DateTimeField(null=True)),
                ('match_outdated', models.BooleanField(default=True)),
                ('match_outdated_360', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_data.competition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('nickname', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('statsbomb_id', models.PositiveSmallIntegerField(unique=True)),
                ('kick_off', models.DateTimeField()),
                ('match_week', models.PositiveSmallIntegerField()),
                ('competition_stage', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('last_updated_360', models.DateTimeField(null=True)),
                ('away_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='raw_data.manager')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='raw_data.team')),
                ('competition_edition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_data.competitionedition')),
                ('home_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='raw_data.manager')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='raw_data.team')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_data.referee')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_data.stadium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competitionedition',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raw_data.season'),
        ),
    ]
