# Generated by Django 4.1.4 on 2022-12-11 18:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionedition',
            name='statsbomb_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='competition_stage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='match_week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
